Part 1!!!!!!!!

In [167]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

In [168]:
data = pd.read_csv("/home/TE/Downloads/31116/3_dsbda/nba.csv")
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
2,John Holland,Boston Celtics,30.0,SG,27.0,6-5,205.0,Boston University,NaN
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
4,Jonas Jerebko,Boston Celtics,8.0,PF,29.0,6-10,231.0,NaN,5000000.0
...,...,...,...,...,...,...,...,...,...
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
454,Raul Neto,Utah Jazz,25.0,PG,24.0,6-1,179.0,NaN,900000.0
455,Tibor Pleiss,Utah Jazz,21.0,C,26.0,7-3,256.0,NaN,2900000.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [169]:
data.isna().sum()

Name         1
Team         1
Number       1
Position     1
Age          1
Height       1
Weight       1
College     85
Salary      12
dtype: int64

In [170]:
data.shape

(458, 9)

In [171]:
data = data.dropna(subset=['Name','Team','Number','Position','Age','Height','Weight','Salary'])

In [172]:


data["College"] = data["College"].fillna(data["College"].mode())
data["Salary"] = data["Salary"].fillna(data["Salary"].mean())
data.dropna(inplace=True)

/tmp/ipykernel_5758/3110100507.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["College"] = data["College"].fillna(data["College"].mode())
/tmp/ipykernel_5758/3110100507.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data["Salary"] = data["Salary"].fillna(data["Salary"].mean())
/tmp/ipykernel_5758/3110100507.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data.dropna(inplace=True)

In [173]:
data

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
...,...,...,...,...,...,...,...,...,...
449,Rodney Hood,Utah Jazz,5.0,SG,23.0,6-8,206.0,Duke,1348440.0
451,Chris Johnson,Utah Jazz,23.0,SF,26.0,6-6,206.0,Dayton,981348.0
452,Trey Lyles,Utah Jazz,41.0,PF,20.0,6-10,234.0,Kentucky,2239800.0
453,Shelvin Mack,Utah Jazz,8.0,PG,26.0,6-3,203.0,Butler,2433333.0
456,Jeff Withey,Utah Jazz,24.0,C,26.0,7-0,231.0,Kansas,947276.0

In [174]:
from sklearn.preprocessing import LabelBinarizer

lb = LabelBinarizer()
data['College'] = lb.fit_transform(data['College'])
data['Team'] = lb.fit_transform(data['Team'])
data['Position'] = lb.fit_transform(data['Position'])
data = data.drop(columns=['Name','Weight'])

/tmp/ipykernel_5758/356383322.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['College'] = lb.fit_transform(data['College'])
/tmp/ipykernel_5758/356383322.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Team'] = lb.fit_transform(data['Team'])
/tmp/ipykernel_5758/356383322.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['Position'] = lb.fit_transform(data['Position'])

In [175]:
grouped_data = data.groupby(data['Height'])
grouped_data.head()

     Team  Number  Position   Age Height  College     Salary
0       0     0.0         0  25.0    6-2        0  7730337.0
1       0    99.0         0  25.0    6-6        0  6796117.0
3       0    28.0         0  22.0    6-5        0  1148640.0
6       0    55.0         0  21.0    6-8        0  1170960.0
7       0    41.0         1  25.0    7-0        0  2165160.0
..    ...     ...       ...   ...    ...      ...        ...
203     0    10.0         0  28.0   5-11        0   211744.0
230     0     2.0         0  31.0    6-1        0  3950313.0
244     0     2.0         0  27.0    6-1        0  6486486.0
329     0     0.0         0  28.0    7-1        0  6110034.0
435     0    11.0         0  24.0    7-1        0  3075880.0

[73 rows x 7 columns]

In [176]:
grouped_data.describe()

        Team                                              Number             \
       count      mean       std  min  25%  50%  75%  max  count       mean
Height
5-11     3.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0    3.0  11.666667
5-9      1.0  0.000000       NaN  0.0  0.0  0.0  0.0  0.0    1.0   4.000000
6-0     10.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   10.0   4.400000
6-1     12.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   12.0  10.083333
6-10    32.0  0.031250  0.176777  0.0  0.0  0.0  0.0  1.0   32.0  21.281250
6-11    29.0  0.034483  0.185695  0.0  0.0  0.0  0.0  1.0   29.0  15.344828
6-2     13.0  0.076923  0.277350  0.0  0.0  0.0  0.0  1.0   13.0  13.923077
6-3     25.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   25.0  11.200000
6-4     28.0  0.035714  0.188982  0.0  0.0  0.0  0.0  1.0   28.0  13.714286
6-5     29.0  0.068966  0.257881  0.0  0.0  0.0  0.0  1.0   29.0  11.344828
6-6     36.0  0.027778  0.166667  0.0  0.0  0.0  0.0  1.0   36.0  14.638889
6-7     37.0  0.027027  0.164399  0.0  0.0  0.0  0.0  1.0   37.0  19.621622
6-8     36.0  0.055556  0.232311  0.0  0.0  0.0  0.0  1.0   36.0  21.361111
6-9     49.0  0.020408  0.142857  0.0  0.0  0.0  0.0  1.0   49.0  22.000000
7-0     20.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0   20.0  23.650000
7-1      3.0  0.000000  0.000000  0.0  0.0  0.0  0.0  0.0    3.0  10.666667
7-2      1.0  0.000000       NaN  0.0  0.0  0.0  0.0  0.0    1.0  17.000000

        ... College      Salary                                          \
        ...     75%  max  count          mean           std         min
Height  ...
5-11    ...     0.0  0.0    3.0  5.891553e+05  7.926627e+05     55722.0
5-9     ...     0.0  0.0    1.0  6.912869e+06           NaN   6912869.0
6-0     ...     0.0  0.0   10.0  5.784075e+06  6.337144e+06    947276.0
6-1     ...     0.0  1.0   12.0  5.456567e+06  4.585905e+06    700902.0
6-10    ...     0.0  0.0   32.0  5.128348e+06  5.325461e+06    222888.0
6-11    ...     0.0  0.0   29.0  5.920326e+06  7.067208e+06    245177.0
6-2     ...     0.0  0.0   13.0  2.558274e+06  2.644553e+06    525093.0
6-3     ...     0.0  0.0   25.0  5.838995e+06  5.987811e+06    189455.0
6-4     ...     0.0  0.0   28.0  4.358526e+06  5.135309e+06    134215.0
6-5     ...     0.0  0.0   29.0  4.363159e+06  4.309770e+06     55722.0
6-6     ...     0.0  1.0   36.0  2.911598e+06  3.195842e+06    167406.0
6-7     ...     0.0  0.0   37.0  3.716167e+06  4.684027e+06    200600.0
6-8     ...     0.0  0.0   36.0  5.616665e+06  5.807020e+06     83397.0
6-9     ...     0.0  1.0   49.0  4.203125e+06  4.760300e+06    111444.0
7-0     ...     0.0  0.0   20.0  5.356997e+06  5.159196e+06    947276.0
7-1     ...     0.0  0.0    3.0  4.331011e+06  1.583467e+06   3075880.0
7-2     ...     0.0  0.0    1.0  1.559222e+07           NaN  15592217.0


                25%         50%          75%         max
Height
5-11      133733.00    211744.0    855872.00   1500000.0
5-9      6912869.00   6912869.0   6912869.00   6912869.0
6-0      2437500.00   3934473.5   4846419.25  21468695.0
6-1      1898610.00   3402626.5   9522106.50  13500000.0
6-10     1021587.00   3750000.0   7003284.00  19689000.0
6-11     1140240.00   2109294.0   8193029.00  22192730.0
6-2       947276.00   1164858.0   3036927.00   8000000.0
6-3      1662360.00   3000000.0   8000000.00  20093064.0
6-4      1006902.75   2515440.0   5167034.25  20000000.0
6-5      1159680.00   3034356.0   6000000.00  16407500.0
6-6       921721.75   1384500.0   3649999.75  11710456.0
6-7       981348.00   1449187.0   3553917.00  16407500.0
6-8      1128220.00   3166666.5   8757132.00  22875000.0
6-9      1000000.00   2489530.0   6268675.00  20158622.0
7-0      1941611.00   3801240.0   6202700.00  19689000.0
7-1      3441500.00   3807120.0   4958577.00   6110034.0
7-2     15592217.00  15592217.0  15592217.00  15592217.0

[17 rows x 48 columns]

In [177]:
type(grouped_data)

pandas.core.groupby.generic.DataFrameGroupBy

In [178]:
grouped_data['Height'].value_counts()

Height
5-11     3
5-9      1
6-0     10
6-1     12
6-10    32
6-11    29
6-2     13
6-3     25
6-4     28
6-5     29
6-6     36
6-7     37
6-8     36
6-9     49
7-0     20
7-1      3
7-2      1
Name: count, dtype: int64

Part 2!!!!!!!!

In [179]:
data2 = pd.read_csv("/home/TE/Downloads/31116/3_dsbda/Iris.csv")
data2

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [180]:
data2.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [181]:
data2['Species'].value_counts()

Species
Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: count, dtype: int64

In [182]:
setosa_species = data2[data2['Species'] == 'Iris-setosa']
setosa_species.describe()

             Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  50.00000       50.00000     50.000000      50.000000      50.00000
mean   25.50000        5.00600      3.418000       1.464000       0.24400
std    14.57738        0.35249      0.381024       0.173511       0.10721
min     1.00000        4.30000      2.300000       1.000000       0.10000
25%    13.25000        4.80000      3.125000       1.400000       0.20000
50%    25.50000        5.00000      3.400000       1.500000       0.20000
75%    37.75000        5.20000      3.675000       1.575000       0.30000
max    50.00000        5.80000      4.400000       1.900000       0.60000

In [183]:
versicolor_species = data2[data2['Species'] == 'Iris-versicolor']
versicolor_species.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000      50.000000     50.000000      50.000000     50.000000
mean    75.50000       5.936000      2.770000       4.260000      1.326000
std     14.57738       0.516171      0.313798       0.469911      0.197753
min     51.00000       4.900000      2.000000       3.000000      1.000000
25%     63.25000       5.600000      2.525000       4.000000      1.200000
50%     75.50000       5.900000      2.800000       4.350000      1.300000
75%     87.75000       6.300000      3.000000       4.600000      1.500000
max    100.00000       7.000000      3.400000       5.100000      1.800000

In [184]:
virginica_species = data2[data2['Species'] == 'Iris-virginica']
virginica_species.describe()

              Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count   50.00000       50.00000     50.000000      50.000000      50.00000
mean   125.50000        6.58800      2.974000       5.552000       2.02600
std     14.57738        0.63588      0.322497       0.551895       0.27465
min    101.00000        4.90000      2.200000       4.500000       1.40000
25%    113.25000        6.22500      2.800000       5.100000       1.80000
50%    125.50000        6.50000      3.000000       5.550000       2.00000
75%    137.75000        6.90000      3.175000       5.875000       2.30000
max    150.00000        7.90000      3.800000       6.900000       2.50000